services:
  builder:
    build:
      context: .
      dockerfile: ./docker/prod/build/Dockerfile
      target: artifact
    environment:
      PHP_VERSION: 8.3
      NODE_VERSION: 24
    volumes:
      - build-artifact:/out
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      retries: 10
      start_period: 20s
  
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
  
  testserver:
    build:
      context: .
      dockerfile: ./docker/prod/server/Dockerfile
    environment:
      PHP_VERSION: 8.3
    volumes:
      - build-artifact:/var/www
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  database-data:
  build-artifact:
    name: laravel-build-artifact