services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3305:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1