name: laravel-development-server

services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        PUID: "${UID:-1000}"
        PGID: "${GID:-1000}"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - appnet
  
  web:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet
  
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: hello_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet
  
  node:
    image: node:22
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  dbdata: